# Perdiz arrow point sample

## 41AN51, Pace McDonald

The Pace McDonald site (41AN51) is a prehistoric Caddo mound center and associated settlement in the upper Neches River basin of east Texas that was established and occupied during the Middle Caddo period (CE 1250-1450). Nine Perdiz arrow points from habitation contexts are in the collections from the site, including eight made from non-local chert (primarily Edwards Plateau chert from Central Texas) and one from a local chert [@RN2444].

## 41AN115

This multi-component prehistoric site is on Town Creek in the Trinity River basin [@RN8982]. Diagnostic projectile points recovered at the site suggest it was occupied from Late Paleoindian times to the Woodland period. There is also a small post-CE 900 ancestral Caddo component marked by three grog-tempered ceramic sherds and one Perdiz point from occupational deposits. The Perdiz point is made from a non-local black chert.

## 41CP5, Tuck Carpenter

The Tuck Carpenter site is a well-studied Late Caddo period Titus phase cemetery on Dry Creek in the Big Cypress Creek basin, and was used by the Caddo from the 15th to the 17th century. Burials with Perdiz points are the earliest in the cemetery, and likely date from CE 1450-1500 [@RN8962, 197]. A single radiocarbon date was obtained from Burial 10: 360 ± 60 BP. The calibrated age range at 2 sigma is CE 1442-1646, with a median probability of CE 1546.

Fifty seven Perdiz points have been recovered from burial features at the Tuck Carpenter site [@RN8963;@RN3158;@RN3159]. A second collection from the site includes an additional 18 Perdiz points from 13 burial features manufactured using Ogallala quartzite and local chert gravel sources; including one that was made from a non-local novaculite [@RN8962, Table 2].

## 41CP12, Johns

The Johns site is a Titus phase cemetery in the Prairie Creek valley of the Big Cypress Creek basin. No radiocarbon dates were obtained from the site, but the decorative motifs associated with the ceramic vessels recovered from burials suggest that the cemetery was used from CE 1450-1600 [@RN2440]. Forty-eight Perdiz points were recovered from 16 burial features. They were made from local chert, quartzite, and silicified wood gravel sources (87 percent), non-local sources (10.8 percent, mainly from Red River gravels), and chalcedony (2.2 percent).

## 41CP20, B. J. Horton

This ancestral Caddo cemetery in the Big Cypress Creek basin includes at least 19 burials, from which two Perdiz points were recovered [@RN2439, 9]. Use of the cemetery by the Caddo occurred primarily between CE 1500-1550 [@RN8964, 494].

## 41CP220, Kitchen Branch

The Kitchen Branch site is located on a small tributary to Prairie Creek in the Big Cypress Creek basin. It is a small Titus phase domestic farmstead occupied during the 15th century CE. During archaeological investigations, five Perdiz points were recovered from habitation contexts [@RN8964], which were manufactured from non-local cherts and novaculite [@RN8964, 410] likely from Red River gravels.

## 41CP495, Sam D. Carpenter Bottom

The Sam D. Carpenter Bottom site rests within an alluvial fan in the Big Cypress Creek valley. It is a single component Late Caddo period Titus phase occupation, likely dating between CE 1500-1550 [@RN2275]. Six Perdiz arrow points are in the site collection from habitation contexts, made from local quartzite (16.7 percent), local brown chert (33.3 percent), and non-local cherts (50 percent). The non-local cherts are from the Ouachita Mountains, and include a gray chert and a brownish-black Big Fork chert.

## 41HS15, Pine Tree Mound Site

The Pine Tree Mound site is a large Titus phase mound center with associated habitation deposits, family cemeteries, and a large community cemetery [@RN5724]. Perdiz arrow points (n = 68) represent 53 percent of the arrow points that could be typed from the site, most (n = 50) from burial contexts and the remainder from habitation deposits. Perdiz points from burial contexts tend to have been made from non-local lithic raw materials, typically chert (42 percent), while none of the non-mortuary Perdiz points are made on non-local raw material [@RN5724, 566].

There are 92 radiocarbon dates available from the Pine Tree Mound site  (Fields and Gadus [-@RN5724, Table 4.13] and Selden Jr. and Perttula [-@RN2944, Table 2]). Most of the calibrated dates fall between CE 1451-1495 and CE 1397-1429 [@RN2944, Table 3], but calibrated age ranges suggest that the settlement “was established in the A.D. 1300s and persisted until at least the mid 1600s” [@RN5724, 299].

## 41HS235, Keasler

The Keasler site is a Late Caddo Titus phase cemetery on a tributary to Little Cypress Creek [@RN8983]. The associated grave goods suggest the cemetery was used by Caddo peoples between CE 1500-1680. The funerary collection from the site includes one Perdiz arrow point made from a local quartzite.

## 41HS269, C. D. Marsh

This ancestral Caddo site is on Eight Mile Creek, a southward-flowing tributary of the Sabine River. Habitation deposits here date from CE 1250-1450 [@RN1536], and a single Perdiz point has been recovered from these deposits. This point is made from a non-local grayish-brown chert.

## Hickory Creek #2, Houston County, Texas

The Hickory Creek #2 site is on an alluvial rise of Hickory Creek, an eastward-flowing tributary of the Neches River [@RN2347]. The site was investigated by the U.S. Forest Service, and has 15th century (Middle Caddo) ancestral Caddo habitation deposits as well as Woodland period deposits. In these deposits are 14 Perdiz arrow points. They are made from local chert (21.4 percent), silicified wood (35.7 percent), local quartzite (35.7 percent), and Glover quartzite (7.1 percent), a non-local raw material that is from the southern Ouachita Mountains and in Red River gravels.

## 41NA49, Washington Square Mound

The Washington Square Mound site is located in the Angelina River basin and is a mound center with associated habitation deposits and a cemetery. Excavations in one mound uncovered two shaft tombs with abundant grave goods, but no Perdiz offerings [@RN914;@RN12]. However, 14 Perdiz points were recovered from a burial feature in the Oak Grove Cemetery portion of the Washington Square Mound site [@RN12, Figure 77]. Another seven Perdiz points came from habitation areas near the main burial mound [@RN8963, Table 14]. Of those, 71 percent are on gray chert of likely central Texas origin, and the remainder were made from local quartzite.

Twelve radiocarbon dates have been obtained from the Washington Square Mound site (Corbin and Hart [-@RN914, Table 4] and Selden Jr. and Perttula [-@RN2944]), indicating use of the site in both Early (CE 900-1250) and Middle Caddo periods (CE 1250-1450). The best dates that can be associated with Perdiz points at the site range from cal. CE 1238-1445.

## 41NA206, Spradley

The Spradley site includes late 17th to early 18th century archaeological deposits with European trade goods from habitation deposits in the Bayou La Nana valley in the Angelina River basin [@RN8965]. Those habitation deposits, which have no associated radiocarbon dates, contain numerous Perdiz points (n = 31). Approximately 94 percent were manufactured from local silicified wood, quartzite, and gravel cherts, and the remainder are from non-local brownish-gray to translucent gray chert, likely from central Texas raw material sources [@RN8965, Table 7].

## 41SA135, Jack Walton

This site is located on Attoyac Bayou [@RN1971], and is an ancestral Caddo site with habitation deposits of likely Middle Caddo period age (CE 1250-1450). There are no radiocarbon dates from the site. Excavations at the site recovered seven Perdiz points.

## 41SM55, Bryan Hardy

The Bryan Hardy site is an ancestral Caddo mound center and settlement on a northern-flowing tributary to the Sabine River [@RN3231]. Radiocarbon dates from the site indicate that it dates to the Middle Caddo period, between CE 1297-1391. One serrated Perdiz arrow point was found in habitation deposits (House 3) at the site. It was manufactured from a non-local grayish-white chert.

## 41SM193, Redwine

The Redwine site (41SM193) site is a Middle Caddo period component located 22 km from the river on a north-flowing tributary (Auburn Creek) of the Sabine River [@RN3230], which includes habitation deposits and a small cemetery. The site has one calibrated date of CE 1300-1454, at 2 sigma, with a median calibrated probability of CE 1356. The 11 Perdiz points from habitation deposits were manufactured on black, brown, and grayish-tan chert as well as Ogallala quartzite [@RN3230, 14]. An additional 13 Perdiz arrow points were among the grave goods recovered from two burial features [@RN3230, 35].

## 41SM195, Wolf

The Wolf site is an ancestral Caddo site also on Auburn Creek. A single 2 sigma calibrated radiocarbon date from a feature in habitation deposits ranges from CE 1315-1440 [@RN3220]. Two Perdiz arrow points have been recovered from the site, both made of a local brown chert [@RN3220, 4-5, Figure 8].

## 41SM442, Alligator Pond

The Alligator Pond site is a multi-component prehistoric habitation site in the Saline Creek valley of the Sabine River basin [@RN2375;@RN2374]. The principal component by ancestral Caddo peoples is between CE 1000-1300. The lithic tool assemblage includes three Perdiz arrow points of non-local chert [@RN2374, Figure 19c, e, j].

## 41SY43, Old Timers'

The Old Timers site is located in the Sabine River basin, and includes post-CE 1400 Late Caddo habitation deposits concentrated in the northern area of the site. Excavations recovered eight Perdiz points, all with serrated blades and made from cherts, 75 percent local gravel cherts, and an additional 25 percent of gray cherts from non-local raw material sources [@RN8966, 77].

## 41SY280, Syb’s Site

This ancestral Caddo site of the Late Caddo Salt Lick phase is located along the Toledo Bend Reservoir, west of the now inundated Sabine River floodplain [@RN8966, Figure 55]. It has a number of habitation clusters that include daub and fired clay from areas of burned ancestral Caddo house structures. There are no radiocarbon dates from the site, but the decorated ceramic vessel sherds in the collection areas suggest that the site relatively dates to a period beginning at CE 1450 through the late CE 1500s. One Perdiz arrow point was recovered from Area 13 of the site [@RN8966, Table 33].
